// GENERATED by `npm run caps:gen` — do not edit.
// One static import per src/levels/data file; registry.ts's import.meta.glob
// can't bundle under wrangler, so the worker resolves level defs through here.
import r0 from '../src/levels/data/01-first-flight.json';
import r1 from '../src/levels/data/02-powder-row.json';
import r2 from '../src/levels/data/03-glass-house.json';
import r3 from '../src/levels/data/04-stone-keep.json';
import r4 from '../src/levels/data/05-hilltop.json';
import r5 from '../src/levels/data/06-lone-guard.json';
import r6 from '../src/levels/data/07-twin-posts.json';
import r7 from '../src/levels/data/08-glass-alley.json';
import r8 from '../src/levels/data/09-tnt-porch.json';
import r9 from '../src/levels/data/10-split-lesson.json';
import r10 from '../src/levels/data/11-heavy-gate.json';
import r11 from '../src/levels/data/12-wheel-yard.json';
import r12 from '../src/levels/data/13-ramp-run.json';
import r13 from '../src/levels/data/14-ledge-nest.json';
import r14 from '../src/levels/data/15-powder-stack.json';
import r15 from '../src/levels/data/16-glass-stack.json';
import r16 from '../src/levels/data/17-hat-row.json';
import r17 from '../src/levels/data/18-blast-shed.json';
import r18 from '../src/levels/data/19-cross-beam.json';
import r19 from '../src/levels/data/20-mixed-yard.json';
import r20 from '../src/levels/data/21-king-court.json';
import r21 from '../src/levels/data/22-triple-keep.json';
import r22 from '../src/levels/data/23-high-perch.json';
import r23 from '../src/levels/data/24-fuse-line.json';
import r24 from '../src/levels/data/25-split-keep.json';
import r25 from '../src/levels/data/26-dash-bridge.json';
import r26 from '../src/levels/data/27-blast-vault.json';
import r27 from '../src/levels/data/28-helmet-keep.json';
import r28 from '../src/levels/data/29-four-roles.json';
import r29 from '../src/levels/data/30-last-stand.json';
import { loadLevelFromJson } from '../src/levels/load';
import type { LevelV2 } from '../src/levels/schema';

export const levelsById: Record<string, LevelV2> = Object.fromEntries(
  [r0, r1, r2, r3, r4, r5, r6, r7, r8, r9, r10, r11, r12, r13, r14, r15, r16, r17, r18, r19, r20, r21, r22, r23, r24, r25, r26, r27, r28, r29].map((raw) => {
    const def = loadLevelFromJson(raw);
    return [def.id, def] as const;
  })
);
