import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { loadLevelFromJson } from '../src/levels/load';
import type { BotKind } from '../src/levels/schema';

// Regenerates docs/LEVEL_CATALOG.md and docs/LEVEL_SOLUTIONS.md from the
// level JSONs, ratings.json and the committed solution books. Run after
// `npm run level:rate` so the rating columns are current.

const dataDir = join(import.meta.dirname, '../src/levels/data');
const repoRoot = join(import.meta.dirname, '..');

const ratings = JSON.parse(
  readFileSync(join(import.meta.dirname, '../src/levels/ratings.json'), 'utf8')
) as {
  seed: string;
  levels: Record<string, { oneShotClear: number; anyKill: number; stars: [number, number, number] }>;
};
const solutions = JSON.parse(
  readFileSync(join(import.meta.dirname, '../src/levels/solutions.json'), 'utf8')
) as Record<string, { shots: { angleDeg: number; speed: number }[]; score: number }>;
const pouch = JSON.parse(
  readFileSync(join(import.meta.dirname, '../src/levels/pouch-solutions.json'), 'utf8')
) as { found: Record<string, { angleDeg: number; speed: number; abilityAt?: number }[]> };

const ARCHETYPE: Record<string, string> = {
  'first-flight': 'tower',
  'powder-row': 'bunker',
  'glass-house': 'bridge',
  'stone-keep': 'tower',
  hilltop: 'stilted',
  'lone-guard': 'tower',
  'twin-posts': 'bridge',
  'glass-alley': 'bunker',
  'tnt-porch': 'castle',
  'split-lesson': 'pyramid',
  'heavy-gate': 'bunker',
  'wheel-yard': 'tower',
  'ramp-run': 'stilted',
  'ledge-nest': 'castle',
  'powder-stack': 'pyramid',
  'glass-stack': 'bridge',
  'hat-row': 'bunker',
  'blast-shed': 'tower',
  'cross-beam': 'bridge',
  'mixed-yard': 'castle',
  'king-court': 'bunker',
  'triple-keep': 'castle',
  'high-perch': 'stilted',
  'fuse-line': 'pyramid',
  'split-keep': 'castle',
  'dash-bridge': 'bridge',
  'blast-vault': 'bunker',
  'helmet-keep': 'tower',
  'four-roles': 'castle',
  'last-stand': 'pyramid',
};

const chapterName: Record<string, string> = {
  training: 'Training Green',
  workshop: 'Dust Workshop',
  citadel: 'Night Citadel',
};

const files = readdirSync(dataDir).filter((f) => f.endsWith('.json')).sort();
const levels = files.map((f) =>
  loadLevelFromJson(JSON.parse(readFileSync(join(dataDir, f), 'utf8')))
);

const seen = new Set<BotKind>();
const introOf = (bots: BotKind[]): string =>
  bots.filter((b) => !seen.has(b) && seen.add(b)).join(',') || '—';

const rows: string[] = [];
for (const l of levels) {
  const r = ratings.levels[l.id];
  const intro = introOf(l.bots);
  rows.push(
    `| ${l.id} | ${l.chapter}-${l.order} | ${l.name} | ${ARCHETYPE[l.id] ?? '?'} | ` +
      `${l.blocks.length} | ${l.pigs.length} | ${l.bots.join('/')} | ${intro} | ` +
      `${r ? r.oneShotClear.toFixed(1) + '%' : '—'} | ${r ? r.anyKill.toFixed(1) + '%' : '—'} | ` +
      `${r ? r.stars.join(' / ') : l.stars.join(' / ')} |`
  );
}

const catalog = `# Level catalog

Generated by \`tools/gen-catalog.ts\` from \`src/levels/data/*.json\` and
\`src/levels/ratings.json\` (rater seed \`${ratings.seed}\`). Do not edit by hand.

Chapters: ${chapterName.training} (10 levels), ${chapterName.workshop} (10),
${chapterName.citadel} (10). Archetypes: tower, bunker, bridge, stilted,
castle, pyramid — no two consecutive levels share one.

| id | chapter-order | name | archetype | blocks | targets | bots | intro | oneShotClear | anyKill | stars (1/2/3) |
|----|---------------|------|-----------|--------|---------|------|-------|--------------|---------|----------------|
${rows.join('\n')}
`;

writeFileSync(join(repoRoot, 'docs/LEVEL_CATALOG.md'), catalog);

const solRows: string[] = [];
for (const l of levels) {
  const s = solutions[l.id];
  const p = pouch.found[l.id];
  const fmt = (shots: { angleDeg: number; speed: number; abilityAt?: number }[] | undefined) =>
    shots
      ? shots
          .map((x) => `${x.angleDeg}°/${x.speed}${x.abilityAt != null ? ` t=${x.abilityAt}` : ''}`)
          .join(' → ')
      : '—';
  solRows.push(
    `| ${l.id} | ${fmt(s?.shots)} | ${s ? s.score.toLocaleString('en-US') : '—'} | ${fmt(p)} |`
  );
}

const solDoc = `# Level solutions

Generated by \`tools/gen-catalog.ts\`. \`solutions.json\` replays from the
sling anchor (physics test book); \`pouch-solutions.json\` replays from the
player pouch through the real input path (\`abilityAt\` = seconds after
launch when the ability fires).

| id | committed shots (angle/speed) | score | pouch shots |
|----|-----------------------------|-------|-------------|
${solRows.join('\n')}
`;

writeFileSync(join(repoRoot, 'docs/LEVEL_SOLUTIONS.md'), solDoc);
console.log('wrote docs/LEVEL_CATALOG.md and docs/LEVEL_SOLUTIONS.md');
